name: Build and Test Feature
on:
  push:
    branches: ["feature/**"]

  pull_request:
    branches: ["develop"]

jobs:
  build:
    name: Build Feature
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/878514427384/locations/global/workloadIdentityPools/githubactions/providers/github'
          service_account: 'ci-cd-service-account@adev-spark.iam.gserviceaccount.com'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Test Gcloud Secrets
        run: |
          gcloud secrets versions access "latest" --secret "my-secret"
      
      - name: Copy Files to GCS
        run: echo "Files Copied to the GCS bucket...."
    
          




