name: Build and Test Feature
on:
  workflow_dispatch:

  push: 
    branches: ["feature/**"]

  pull_request: 
    branches: ["develop", "main"]

jobs:
  authenticate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: "auth"
        name: Authenticate to GCP
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/878514427384/locations/global/workloadIdentityPools/githubactionspool/providers/github-provider"
          service_account: "wkf-oidc@adev-spark.iam.gserviceaccount.com"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Test 
        run: |
          gsutil ls
      - name: Upload Test Files to Storage Bucket
        run: |
          gsutil cp -r source/dataProcessingCode/src/tests gs://pyspark-testing-adev-spark
          
