name: Build and Test Feature
on:
  push:
    branches: ["feature/**"]

  pull_request:
    branches: ["develop"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SA: ${{ secrets.GCP_SA }}
  SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  build:
    name: Build Feature
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/878514427384/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'dev-github-resource-access-sa@adev-spark.iam.gserviceaccount.com'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      #     project_id: ${{ env.PROJECT_ID }}
      #     service_account_key: ${{ env.SA_KEY }}

      - name: Test Gcloud
        run: |
          gcloud config set account aravind.dev83@gmail.com
          gcloud config set project adev-spark
          gcloud auth list
          gcloud version
          gsutil ls

      # - name: Validate Authentication
      #   run: gcloud info
      # - name: Install Gcloud SDK
      #   run: sudo apt-get update && sudo apt-get install -y google-cloud-sdk
      
      - name: Copy Files to GCS
        run: echo "Files Copied to the GCS bucket...."
    
          




