name: Second Sample Worflow
on: workflow_dispatch
jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          ref: feature/PYSBDL-1
      - name: Install Python 3.9.16
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9.16
      - name: Install dependencies with Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile
      - name: Run Unit Test
        run: python source/dataProcessingCode/src/tests/unit/test_job.py
      